services:
  streamlit:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: acme-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      TRACE_VIEWER_URL: http://localhost:16686
  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: acme-api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - keycloak
      - mcp_server
    environment:
      MCP_API_KEY: "acme-internal-secret-2024"
      MCP_BASE_URL: http://mcp_server:8100
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALM: acme
      KEYCLOAK_AUDIENCE: acme-api
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      POSTGRES_DB: acme
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: acme123
      POSTGRES_PORT: 5432
      POSTGRES_USER: acme
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_TTL_SECONDS: 86400
      GROQ_API_KEY: ${GROQ_API_KEY}
      TRACE_PROVIDER_URL: http://jaeger:4317
  mcp_server:
    build:
      context: .
      dockerfile: mcp_server/Dockerfile
    container_name: acme-mcp
    ports:
      - "8100:8100"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    environment:
      MCP_API_KEY: "acme-internal-secret-2024"
      POSTGRES_DB: acme
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: acme123
      POSTGRES_PORT: 5432
      POSTGRES_USER: acme
      MCP_HOST: 0.0.0.0
      MCP_PORT: 8100
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: acme-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
  postgres:
    image: postgres:16
    container_name: acme-postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U acme"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: acme
      POSTGRES_USER: acme
      POSTGRES_PASSWORD: acme123
    ports:
      - "5432:5432"
    volumes:
      - ./seed/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7
    container_name: acme-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.2
    container_name: acme-keycloak
    command: start-dev --import-realm
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json